const content = [
    //Hero.customizable.jsx
    { section: 'hero', key: 'carousel1Title', defaultValue: 'Luxury Times.<br />Bay & Beyond.' },
    { section: 'hero', key: 'carousel1Subtitle', defaultValue: 'The finest hotel near Panama Beach' },
    { section: 'hero', key: 'carousel1ButtonText', defaultValue: 'VIEW EXCLUSIVE ROOMS' },
    { section: 'hero', key: 'carousel2Title', defaultValue: 'Comfort & More.<br />Bay & Beyond.' },
    { section: 'hero', key: 'carousel2Subtitle', defaultValue: 'The finest hotel near Panama Beach' },
    { section: 'hero', key: 'image1', defaultValue: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?q=80&w=1471&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    { section: 'hero', key: 'image2', defaultValue: 'https://images.unsplash.com/photo-1621293954908-907159247fc8?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    //Rooms.customizable.jsx
    { section: 'rooms', key: 'roomsTitle', defaultValue: 'Eco-Inspired Lodging' },
    { section: 'rooms', key: 'roomsSubtitle', defaultValue: 'ACCOMMODATION & COMFORT' },
    { section: 'rooms', key: 'penthouseSuiteTitle', defaultValue: 'Penthouse Suite' },
    { section: 'rooms', key: 'penthouseSuiteDescription', defaultValue: 'Luxurious suite with panoramic views.' },
    { section: 'rooms', key: 'janitorSuiteTitle', defaultValue: 'Janitor Suite' },
    { section: 'rooms', key: 'janitorSuiteDescription', defaultValue: 'Comfortable suite with a quaint charm.' },
    { section: 'rooms', key: 'familyDoubleTitle', defaultValue: 'Family Double Room' },
    { section: 'rooms', key: 'familyDoubleDescription', defaultValue: 'Spacious room ideal for families.' },
    { section: 'rooms', key: 'executiveRoomTitle', defaultValue: 'Executive Room' },
    { section: 'rooms', key: 'executiveRoomDescription', defaultValue: 'Elegantly designed room for business travelers.' },
    { section: 'rooms', key: 'emptyTitleRoomTitle', defaultValue: 'Empty Room' },
    { section: 'rooms', key: 'emptyTitleRoomDescription', defaultValue: 'A room that’s ready for your next stay.' },
    { section: 'rooms', key: 'image1', defaultValue: 'https://images.unsplash.com/photo-1657907157592-dd6cfb9d06cf?q=80&w=1400&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    { section: 'rooms', key: 'image2', defaultValue: 'https://plus.unsplash.com/premium_photo-1661780295073-98db12600af0?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    { section: 'rooms', key: 'image3', defaultValue: 'https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=1632&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    { section: 'rooms', key: 'image4', defaultValue: 'https://images.unsplash.com/photo-1615874694520-474822394e73?q=80&w=1480&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    { section: 'rooms', key: 'image5', defaultValue: 'https://images.unsplash.com/photo-1600494448850-6013c64ba722?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    //HomeAmbience.customizable.jsx
    { section: 'ambience', key: 'title', defaultValue: 'Get Home-like Ambience' },
    { section: 'ambience', key: 'description', defaultValue: 'A self-described luxury temporary residence, the AKA Beverly Hills offers guests the space and comfort of an apartment, with the service and amenities you’d expect at a five-star hotel.' },
    { section: 'ambience', key: 'buttonText', defaultValue: 'VIEW EXCLUSIVE ROOM' },
    { section: 'ambience', key: 'image', defaultValue: 'https://images.unsplash.com/photo-1602081115720-72e5b0a254b8?q=80&w=1471&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    //Parralax.customizable.jsx
    { section: 'parallax', key: 'section1Subtitle', defaultValue: 'ACCOMMODATION & COMFORT' },
    { section: 'parallax', key: 'section1Title', defaultValue: 'Eco-Inspired Lodging' },
    { section: 'parallax', key: 'parallax1Subtitle', defaultValue: 'Explore. Wander. Disappear.' },
    { section: 'parallax', key: 'parallax1Title', defaultValue: 'The Great Escape<br />You\'ll Remember.' },
    { section: 'parallax', key: 'section2Subtitle', defaultValue: 'People Love Our Hotel' },
    { section: 'parallax', key: 'section2Title', defaultValue: 'What Others Say' },
    { section: 'parallax', key: 'parallax2Subtitle', defaultValue: 'Enjoy with your partner.' },
    { section: 'parallax', key: 'parallax2Title', defaultValue: 'Honeymoon Package<br />50% Off' },
    { section: 'parallax', key: 'buttonText', defaultValue: 'VIEW EXCLUSIVE ROOM' },
    { section: 'parallax', key: 'grid1Title', defaultValue: 'Airport Pickup' },
    { section: 'parallax', key: 'grid1Description', defaultValue: 'We’ll pick up from airport while you comfy on your ride.' },
    { section: 'parallax', key: 'grid2Title', defaultValue: 'Food Service' },
    { section: 'parallax', key: 'grid2Description', defaultValue: 'We’ll ensure you’re well-fed with our room service options.' },
    { section: 'parallax', key: 'grid3Title', defaultValue: 'City Tour' },
    { section: 'parallax', key: 'grid3Description', defaultValue: 'Explore the city with our guided tours.' },
    { section: 'parallax', key: 'grid4Title', defaultValue: 'Beach Access' },
    { section: 'parallax', key: 'grid4Description', defaultValue: 'Enjoy the sun with our beach access.' },
    { section: 'parallax', key: 'review1Name', defaultValue: 'Joanna Roberts' },
    { section: 'parallax', key: 'review1Text', defaultValue: '“This was the perfect hotel with the perfect location, perfect room; I couldn’t think of a more perfect trip! This was a great location as I was going to a conference at the Javitz center and it’s nearly a couple blocks walk.”' },
    { section: 'parallax', key: 'review2Name', defaultValue: 'Emily Davis' },
    { section: 'parallax', key: 'review2Text', defaultValue: '“Fantastic stay! The staff was incredibly friendly and the amenities were top-notch. Highly recommend!”' },
    { section: 'parallax', key: 'review3Name', defaultValue: 'Michael Brown' },
    { section: 'parallax', key: 'review3Text', defaultValue: '“An unforgettable experience! The location was ideal, and the service was exceptional. Will definitely return.”' },
    { section: 'parallax', key: 'image1', defaultValue: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    { section: 'parallax', key: 'image2', defaultValue: 'https://plus.unsplash.com/premium_photo-1661901734877-88919d011b24?q=80&w=1480&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    //Best.Customizable.jsx
    { section: 'best', key: 'whatsUp', defaultValue: "What's Up" },
    { section: 'best', key: 'bestValues', defaultValue: 'Best Values' },
    { section: 'best', key: 'smallRoomTitle1', defaultValue: 'Small Room 1' },
    { section: 'best', key: 'smallRoomPrice1', defaultValue: '10' },
    { section: 'best', key: 'freeWifi1', defaultValue: 'Free Wifi' },
    { section: 'best', key: 'greatSeaView1', defaultValue: 'Great Sea View' },
    { section: 'best', key: 'homeMadeFood1', defaultValue: 'Home-made Food' },
    { section: 'best', key: 'roomShare1', defaultValue: 'Room Share' },
    { section: 'best', key: 'acBathtub1', defaultValue: 'AC & Bathtub' },
    { section: 'best', key: 'smallRoomTitle2', defaultValue: 'Small Room 2' },
    { section: 'best', key: 'smallRoomPrice2', defaultValue: '15' },
    { section: 'best', key: 'freeWifi2', defaultValue: 'Free Wifi' },
    { section: 'best', key: 'greatSeaView2', defaultValue: 'Great Sea View' },
    { section: 'best', key: 'homeMadeFood2', defaultValue: 'Home-made Food' },
    { section: 'best', key: 'roomShare2', defaultValue: 'Room Share' },
    { section: 'best', key: 'acBathtub2', defaultValue: 'AC & Bathtub' },
    { section: 'best', key: 'roomTitle3', defaultValue: 'Room Title 3' },
    { section: 'best', key: 'roomPrice3', defaultValue: '27' },
    { section: 'best', key: 'freeWifi3', defaultValue: 'Free Wifi' },
    { section: 'best', key: 'greatSeaView3', defaultValue: 'Great Sea View' },
    { section: 'best', key: 'homeMadeFood3', defaultValue: 'Home-made Food' },
    { section: 'best', key: 'roomShare3', defaultValue: 'Room Share' },
    { section: 'best', key: 'acBathtub3', defaultValue: 'AC & Bathtub' }
];

export default content;